# Generated by Django 5.0.3 on 2024-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
