# Generated by Django 5.0.3 on 2024-03-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paticipants',
            new_name='Participants',
        ),
    ]
