# Generated by Django 5.0.3 on 2024-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=20, verbose_name='Last Name')),
                ('fatherName', models.CharField(max_length=20, verbose_name='Father Name')),
                ('certificateId', models.CharField(max_length=10, verbose_name='National Id')),
                ('marriageSituate', models.CharField(blank=True, choices=[('SN', 'Single'), ('MR', 'Married')], max_length=50, null=True, verbose_name='Married Situate')),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('birthdayDate', models.DateField(verbose_name='Date of Birthday')),
                ('phone', models.CharField(max_length=11, verbose_name='Mobile Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
    ]
