# Generated by Django 5.0.3 on 2024-03-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_rename_certificateid_hiring_nationalid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='marriageSituate',
        ),
    ]
