# Generated by Django 5.0.3 on 2024-03-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_remove_hiring_marriagesituate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='marriageSituate',
            field=models.CharField(blank=True, choices=[('SN', 'Single'), ('MR', 'Married')], max_length=50, null=True, verbose_name='Married Situate'),
        ),
    ]
