# Generated by Django 5.0.3 on 2024-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_hiring_marriagesituate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='fileUpload',
        ),
        migrations.AlterField(
            model_name='hiring',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
    ]
