# Generated by Django 5.0.3 on 2024-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_hiring_nationalid_hiring_address_hiring_birthdaydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='firstName',
            field=models.CharField(default=False, max_length=20, verbose_name='First Name'),
            preserve_default=False,
        ),
    ]
