# Generated by Django 5.0.3 on 2024-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_alter_hiring_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='marriageSituate',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True, verbose_name='Married Situate'),
        ),
    ]
