# Generated by Django 5.0.3 on 2024-03-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_hiring_city_alter_hiring_marriagesituate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='fileUpload',
            field=models.FileField(blank=True, null=True, storage='Media/', upload_to=''),
        ),
    ]
