# Generated by Django 5.0.3 on 2024-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_alter_hiring_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='fileUpload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
