# Generated by Django 5.0.3 on 2024-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_alter_hiring_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='marriageSituate',
            field=models.CharField(blank=True, choices=[('SN', 'Single'), ('MR', 'Married')], max_length=50, null=True, verbose_name='Married Situate'),
        ),
    ]
