# Generated by Django 5.0.3 on 2024-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0012_alter_hiring_city_alter_hiring_marriagesituate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='fileUpload',
            field=models.FileField(upload_to=''),
        ),
    ]
