# Generated by Django 5.0.3 on 2024-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0013_alter_hiring_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='fileUpload',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
